export { useOcrSettings } from './ocr'
export { useTranslationSettings } from './translation'
export { useDetectionSettings } from './detection'
export { useHqTranslationSettings } from './hqTranslation'
export { usePluginAgentSettings } from './pluginAgent'
export { useProofreadingSettings } from './proofreading'
export { usePromptsSettings } from './prompts'
export { useMiscSettings } from './misc'
export { useWebImportSettings, createDefaultWebImportSettings } from './webImport'
