import {
  AlertTriangle,
  AlignCenter,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignLeft,
  AlignRight,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  BookMarked,
  BookOpen,
  Brush,
  Camera,
  CaseSensitive,
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Check,
  Clock3,
  ClipboardCopy,
  Circle,
  Columns2,
  Download,
  Eraser,
  Eye,
  EyeOff,
  FileText,
  FolderGit,
  FolderOpen,
  Globe2,
  GripVertical,
  HelpCircle,
  Home,
  Image,
  Keyboard,
  Languages,
  Link2,
  List,
  LoaderCircle,
  Lock,
  MapPin,
  Maximize2,
  MessageSquare,
  Minus,
  Moon,
  Monitor,
  MousePointer2,
  Palette,
  Paintbrush,
  Pencil,
  Pause,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Rows2,
  Save,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  SquareMinus,
  SquarePlus,
  Sun,
  Tags,
  Target,
  Trash2,
  Type,
  Upload,
  Users,
  WandSparkles,
  X,
} from '@lucide/vue'
import type { LucideIcon } from '@lucide/vue'

export const uiIconRegistry = {
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-horizontal-center': AlignHorizontalJustifyCenter,
  'align-horizontal-end': AlignHorizontalJustifyEnd,
  'align-horizontal-start': AlignHorizontalJustifyStart,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'align-vertical-center': AlignVerticalJustifyCenter,
  'align-vertical-end': AlignVerticalJustifyEnd,
  'align-vertical-start': AlignVerticalJustifyStart,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bar-chart': BarChart3,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  brush: Brush,
  camera: Camera,
  'case-sensitive': CaseSensitive,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  check: Check,
  clock: Clock3,
  circle: Circle,
  copy: ClipboardCopy,
  columns: Columns2,
  download: Download,
  eraser: Eraser,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  github: FolderGit,
  'folder-open': FolderOpen,
  globe: Globe2,
  'grip-vertical': GripVertical,
  'help-circle': HelpCircle,
  home: Home,
  image: Image,
  keyboard: Keyboard,
  languages: Languages,
  link: Link2,
  list: List,
  loading: LoaderCircle,
  lock: Lock,
  'map-pin': MapPin,
  maximize: Maximize2,
  message: MessageSquare,
  minus: Minus,
  moon: Moon,
  monitor: Monitor,
  'mouse-pointer': MousePointer2,
  palette: Palette,
  paintbrush: Paintbrush,
  pencil: Pencil,
  pause: Pause,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  rows: Rows2,
  save: Save,
  'scan-line': ScanLine,
  'scan-search': ScanSearch,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  'square-minus': SquareMinus,
  'square-plus': SquarePlus,
  sun: Sun,
  tags: Tags,
  target: Target,
  trash: Trash2,
  type: Type,
  upload: Upload,
  users: Users,
  'wand-sparkles': WandSparkles,
  x: X,
} satisfies Record<string, LucideIcon>

export type UiIconName = keyof typeof uiIconRegistry
